"""sprint 6 graph knowledge

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-05 21:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_knowledge_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('subject_label', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_label', sa.String(), nullable=False),
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_model', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('neo4j_rel_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_uuid'], ['knowledge_documents.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_knowledge_candidates_chunk_id'), 'graph_knowledge_candidates', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_graph_knowledge_candidates_document_uuid'), 'graph_knowledge_candidates', ['document_uuid'], unique=False)
    op.create_index(op.f('ix_graph_knowledge_candidates_review_status'), 'graph_knowledge_candidates', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_knowledge_candidates_review_status'), table_name='graph_knowledge_candidates')
    op.drop_index(op.f('ix_graph_knowledge_candidates_document_uuid'), table_name='graph_knowledge_candidates')
    op.drop_index(op.f('ix_graph_knowledge_candidates_chunk_id'), table_name='graph_knowledge_candidates')
    op.drop_table('graph_knowledge_candidates')
    # ### end Alembic commands ###
