"""sprint 6 graph knowledge

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-05 21:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_knowledge_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_uuid', sa.UUID(), nullable=False, comment='UUID of the parent KnowledgeDocument'),
    sa.Column('chunk_id', sa.UUID(), nullable=False, comment='UUID of the DocumentChunk (= Qdrant point_id)'),
    sa.Column('page_number', sa.Integer(), nullable=False, default=0, comment='Page within the source document (1-based)'),
    sa.Column('authority', sa.String(length=200), nullable=False, default='', comment='Publishing authority from document metadata'),
    sa.Column('subject_label', sa.String(length=100), nullable=False, comment='Ontology node type (e.g. Crop)'),
    sa.Column('subject_name', sa.String(length=300), nullable=False, comment='Canonical entity name'),
    sa.Column('predicate', sa.String(length=100), nullable=False, comment='Relationship type (e.g. HAS_DISEASE)'),
    sa.Column('object_label', sa.String(length=100), nullable=False, comment='Ontology node type of the target'),
    sa.Column('object_name', sa.String(length=300), nullable=False, comment='Canonical entity name of the target'),
    sa.Column('source_text', sa.Text(), nullable=True, comment='Text evidence that produced this relationship'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Extraction confidence 0.0-1.0'),
    sa.Column('extraction_model', sa.String(length=100), nullable=False, comment='Extractor identifier'),
    sa.Column('review_status', sa.String(length=20), nullable=False, comment='PENDING | APPROVED | REJECTED'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='UUID of the reviewing officer (from User.uuid)'),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('neo4j_rel_id', sa.String(length=100), nullable=True, comment='The rel_id of the resulting Neo4j relationship'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunk.chunk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_uuid'], ['knowledge_document.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gkc_document_status', 'graph_knowledge_candidate', ['document_uuid', 'review_status'], unique=False)
    op.create_index('ix_gkc_predicate', 'graph_knowledge_candidate', ['predicate'], unique=False)
    op.create_index('ix_gkc_subject', 'graph_knowledge_candidate', ['subject_label', 'subject_name'], unique=False)
    op.create_index(op.f('ix_graph_knowledge_candidate_chunk_id'), 'graph_knowledge_candidate', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_graph_knowledge_candidate_document_uuid'), 'graph_knowledge_candidate', ['document_uuid'], unique=False)
    op.create_index(op.f('ix_graph_knowledge_candidate_review_status'), 'graph_knowledge_candidate', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_knowledge_candidate_review_status'), table_name='graph_knowledge_candidate')
    op.drop_index(op.f('ix_graph_knowledge_candidate_document_uuid'), table_name='graph_knowledge_candidate')
    op.drop_index(op.f('ix_graph_knowledge_candidate_chunk_id'), table_name='graph_knowledge_candidate')
    op.drop_index('ix_gkc_subject', table_name='graph_knowledge_candidate')
    op.drop_index('ix_gkc_predicate', table_name='graph_knowledge_candidate')
    op.drop_index('ix_gkc_document_status', table_name='graph_knowledge_candidate')
    op.drop_table('graph_knowledge_candidate')
    # ### end Alembic commands ###
