"""sprint 7 vision

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-09 16:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('owner_uuid', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('crop_hint', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_images_field_id'), 'crop_images', ['field_id'], unique=False)
    op.create_index(op.f('ix_crop_images_file_hash'), 'crop_images', ['file_hash'], unique=True)
    op.create_index(op.f('ix_crop_images_owner_uuid'), 'crop_images', ['owner_uuid'], unique=False)
    op.create_index(op.f('ix_crop_images_uuid'), 'crop_images', ['uuid'], unique=True)
    
    op.create_table('image_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_issues', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['crop_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_analyses_image_id'), 'image_analyses', ['image_id'], unique=False)
    op.create_index(op.f('ix_image_analyses_status'), 'image_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_image_analyses_uuid'), 'image_analyses', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_analyses_uuid'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_status'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_image_id'), table_name='image_analyses')
    op.drop_table('image_analyses')
    op.drop_index(op.f('ix_crop_images_uuid'), table_name='crop_images')
    op.drop_index(op.f('ix_crop_images_owner_uuid'), table_name='crop_images')
    op.drop_index(op.f('ix_crop_images_file_hash'), table_name='crop_images')
    op.drop_index(op.f('ix_crop_images_field_id'), table_name='crop_images')
    op.drop_table('crop_images')
    # ### end Alembic commands ###
