"""sprint 8 voice

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-18 21:05:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('audio_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('owner_uuid', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('language_detected', sa.String(length=10), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_records_file_hash'), 'audio_records', ['file_hash'], unique=True)
    op.create_index(op.f('ix_audio_records_language_detected'), 'audio_records', ['language_detected'], unique=False)
    op.create_index(op.f('ix_audio_records_owner_uuid'), 'audio_records', ['owner_uuid'], unique=False)
    op.create_index(op.f('ix_audio_records_uuid'), 'audio_records', ['uuid'], unique=True)
    
    op.create_table('speech_transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=20), nullable=False),
    sa.Column('language_confidence', sa.Float(), nullable=False),
    sa.Column('transcription_confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=True),
    sa.Column('detected_intent', sa.String(length=100), nullable=True),
    sa.Column('extracted_entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_transcripts_audio_id'), 'speech_transcripts', ['audio_id'], unique=False)
    op.create_index(op.f('ix_speech_transcripts_detected_language'), 'speech_transcripts', ['detected_language'], unique=False)
    op.create_index(op.f('ix_speech_transcripts_uuid'), 'speech_transcripts', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_speech_transcripts_uuid'), table_name='speech_transcripts')
    op.drop_index(op.f('ix_speech_transcripts_detected_language'), table_name='speech_transcripts')
    op.drop_index(op.f('ix_speech_transcripts_audio_id'), table_name='speech_transcripts')
    op.drop_table('speech_transcripts')
    op.drop_index(op.f('ix_audio_records_uuid'), table_name='audio_records')
    op.drop_index(op.f('ix_audio_records_owner_uuid'), table_name='audio_records')
    op.drop_index(op.f('ix_audio_records_language_detected'), table_name='audio_records')
    op.drop_index(op.f('ix_audio_records_file_hash'), table_name='audio_records')
    op.drop_table('audio_records')
    # ### end Alembic commands ###
